### ISSUE TITLE
Milestone Tracking: Protoss Structures

### ISSUE THREAD

**Issue by heinermann** [heinermann/factorio-starcraft#13]
- [x] Structure entities
- [x] Pylon power/psi requirements
- [x] Powered/unpowered states
- [x] Idle/Working animation states
- [x] Shields
- [x] Shield regen
- [x] Photon Cannon
- [x] Building construction and Warp-in
- [ ] Shield Battery Energy
- [x] Fire overlays
- [x] Shield hit overlay
- [ ] Assimilator
