### ISSUE TITLE
Milestone Tracking: Terran Structures

### ISSUE THREAD

**Issue by heinermann** [heinermann/factorio-starcraft#15]
- [ ] Structure entities
- [ ] Idle/Working animation states
- [ ] Missile Turret
- [ ] Bunker
- [ ] Addons
- [ ] Comsat Station Energy
- [ ] Liftoff/Landing
- [ ] Lifting/landing dust
- [ ] Building construction and partial construction anim states
- [x] Fire overlays
- [ ] Low HP burn down
- [ ] Repair
- [ ] Refinery
